### ISSUE TITLE
工具真的很 nice， 提两个需求，并分享一下我的 css 样式

### ISSUE THREAD

**Issue by Mayandev** [zhning12/markdown-nice#6]
需求：

- css 增加缓存功能
- 微信外链自动转引用
- 引用里，中文和链接之间自动换行，不然在手机上排版会乱。

另外，这是我的 css 样式，欢迎大家使用。
- 增加了三号标题的背景颜色（可根据自己主题风格调整），以及内边距
- 字体间距调整为 3px，字体大小调整为 17px，阅读更加舒适
- 图片增加了 5px 圆角
- 分割线改为浅灰色虚线

```css
/*自定义样式，实时生效*/

/* 全局属性
 * 页边距 padding: 30px;
 * 全文字体 font-family: ptima-Regular;
 */
.layout {
}

/* 段落，下方未标注标签参数均同此处
 * 上边距 margin-top: 5px;
 * 下边距 margin-bottom: 5px;
 * 行高 line-height: 26px;
 * 对齐 text-align: left;
 * 颜色 color: #3e3e3e;
 * 字体大小 font-size: 16px;
 * 首行缩进 text-indent: 2em;
 */
p {
  font-size: 17px;
  word-spacing: 3px;
  letter-spacing: 1px
}

/* 一级标题 */
h1 {
}

/* 一级标题内容 */
h1 span {
}

/* 一级标题修饰 请参考有实例的主题 */
h1:after {
}

/* 二级标题 */
h2 {
}

/* 二级标题内容 */
h2 span {
}

/* 二级标题修饰 请参考有实例的主题 */
h2:after {
}

/* 三级标题 */
h3 {
}

/* 三级标题内容 */
h3 span {
  background-color: #5c5c5c;
  color: white;
  padding: 5px 15px;
  border-radius: 1px;
}

/* 三级标题修饰 请参考有实例的主题 */
h3:after {
}

/* 列表内容 */
li {
}

/* 引用
* 左边缘颜色 border-left-color: black;
* 背景色 background: gray;
*/
blockquote {
}

/* 引用文字 */
blockquote p {
}

/* 链接 */
a {
}

/* 加粗 */
strong {
}

/* 斜体 */
em {
}

/* 加粗斜体 */
strong em {
}

/* 删除线 */
del {
  
}

/* 分隔线
* 粗细、样式和颜色
* border-top: 1px solid #3e3e3e;
*/
hr {
  border-top: 1px dashed #dddddd;
}

/* 图片
* 宽度 width: 80%;
* 居中 margin: 0 auto;
* 居左 margin: 0 0;
*/
img {
  border-radius: 5px;
}

/* 图片描述文字 */
figcaption {
}

/* 脚注上标 */
.footnote-ref {

}

/* 脚注参考资料文字 
 * 隐藏 display: none;
 */
.footnotes-sep {

}
```
