### ISSUE TITLE
blockquote引用问题

### ISSUE THREAD

**Issue by ZongchengMa** [zhning12/markdown-nice#8]
看起来，微信似乎不支持 `blockquote:before` 和 `blockquote:after` 样式。不知开发者是否有其他兼容的点子？

以下是我的 blockquote 样式代码：
``` CSS
blockquote {
    font-size: 1em;
    font-style: normal;
    padding: 30px 38px;
    margin: 0 0 15px;
    position: relative;
    line-height: 1.8;
    text-indent: 0;
    border: none;
    color: #888;
    background: #FFFFFF
}
​
blockquote:before {
    content: "“";
    left: 12px;
    top: 0;
    color: #E0E0E0;
    font-size: 4em;
    font-family: Arial, serif;
    line-height: 1em;
    font-weight: 700;
    position: absolute;
}
​
blockquote:after {
    content: "”";
    right: 12px;
    bottom: -26px;
    color: #E0E0E0;
    font-size: 4em;
    font-family: Arial, serif;
    line-height: 1em;
    font-weight: 700;
    position: absolute;
    bottom: -31px;
}
```

以下是 https://mdnice.github.io/ 的显示效果：
![image](https://user-images.githubusercontent.com/48177061/56807767-4e39b800-6862-11e9-9160-f5be2f23838e.png)

以下为复制到微信公众号编辑器后的显示效果：
![image](https://user-images.githubusercontent.com/48177061/56807814-6ad5f000-6862-11e9-929f-09068d3c18ff.png)

不过，目前该编辑器已经符合了我的大部分需求，请允许我向你们致谢。
